version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  telephony-app:
    build:
      context: ./telephony-service
      dockerfile: Dockerfile
    container_name: "telephony-app"
    ports:
      - "3001:3000"
  
  agentic-service:
    build:
      context: ./agentic-service
      dockerfile: Dockerfile
    container_name: "agentic-service"
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - AWS_PROFILE=macbook
    ports:
      - "3002:3000"
    depends_on:
      - redis

volumes:
  redis_data: